// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SsmUIClient is the client API for SsmUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SsmUIClient interface {
	// ListSidecarSpecs returns a list of Service Sidecar(s) that can be started through the UI.
	ListSidecarSpecs(ctx context.Context, in *ListSidecarSpecsRequest, opts ...grpc.CallOption) (SsmUI_ListSidecarSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type ssmUIClient struct {
	cc grpc.ClientConnInterface
}

func NewSsmUIClient(cc grpc.ClientConnInterface) SsmUIClient {
	return &ssmUIClient{cc}
}

func (c *ssmUIClient) ListSidecarSpecs(ctx context.Context, in *ListSidecarSpecsRequest, opts ...grpc.CallOption) (SsmUI_ListSidecarSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SsmUI_ServiceDesc.Streams[0], "/v1.SsmUI/ListSidecarSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &ssmUIListSidecarSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SsmUI_ListSidecarSpecsClient interface {
	Recv() (*ListSidecarSpecsResponse, error)
	grpc.ClientStream
}

type ssmUIListSidecarSpecsClient struct {
	grpc.ClientStream
}

func (x *ssmUIListSidecarSpecsClient) Recv() (*ListSidecarSpecsResponse, error) {
	m := new(ListSidecarSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ssmUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.SsmUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SsmUIServer is the server API for SsmUI service.
// All implementations must embed UnimplementedSsmUIServer
// for forward compatibility
type SsmUIServer interface {
	// ListSidecarSpecs returns a list of Service Sidecar(s) that can be started through the UI.
	ListSidecarSpecs(*ListSidecarSpecsRequest, SsmUI_ListSidecarSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedSsmUIServer()
}

// UnimplementedSsmUIServer must be embedded to have forward compatible implementations.
type UnimplementedSsmUIServer struct {
}

func (UnimplementedSsmUIServer) ListSidecarSpecs(*ListSidecarSpecsRequest, SsmUI_ListSidecarSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListSidecarSpecs not implemented")
}
func (UnimplementedSsmUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedSsmUIServer) mustEmbedUnimplementedSsmUIServer() {}

// UnsafeSsmUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SsmUIServer will
// result in compilation errors.
type UnsafeSsmUIServer interface {
	mustEmbedUnimplementedSsmUIServer()
}

func RegisterSsmUIServer(s grpc.ServiceRegistrar, srv SsmUIServer) {
	s.RegisterService(&SsmUI_ServiceDesc, srv)
}

func _SsmUI_ListSidecarSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListSidecarSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SsmUIServer).ListSidecarSpecs(m, &ssmUIListSidecarSpecsServer{stream})
}

type SsmUI_ListSidecarSpecsServer interface {
	Send(*ListSidecarSpecsResponse) error
	grpc.ServerStream
}

type ssmUIListSidecarSpecsServer struct {
	grpc.ServerStream
}

func (x *ssmUIListSidecarSpecsServer) Send(m *ListSidecarSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SsmUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SsmUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SsmUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SsmUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SsmUI_ServiceDesc is the grpc.ServiceDesc for SsmUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SsmUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.SsmUI",
	HandlerType: (*SsmUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _SsmUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListSidecarSpecs",
			Handler:       _SsmUI_ListSidecarSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ssm-ui.proto",
}
