// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SsmServiceClient is the client API for SsmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SsmServiceClient interface {
	// StartLocalSidecar starts a Service Sidecar on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the ssm/config.yaml
	//   3. all bytes constituting the Sidecar YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalSidecar(ctx context.Context, opts ...grpc.CallOption) (SsmService_StartLocalSidecarClient, error)
	// StartFromPreviousSidecar starts a new Sidecar based on a previous one.
	// If the previous Sidecar does not have the can-replay condition set this call will result in an error.
	StartFromPreviousSidecar(ctx context.Context, in *StartFromPreviousSidecarRequest, opts ...grpc.CallOption) (*StartSidecarResponse, error)
	// StartSidecarRequest starts a new Sidecar based on its specification.
	StartSidecar(ctx context.Context, in *StartSidecarRequest, opts ...grpc.CallOption) (*StartSidecarResponse, error)
	// Searches for Sidecar(s) known to this Sidecar
	ListSidecars(ctx context.Context, in *ListSidecarsRequest, opts ...grpc.CallOption) (*ListSidecarsResponse, error)
	// Subscribe listens to new Sidecar(s) updates
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (SsmService_SubscribeClient, error)
	// GetSidecar retrieves details of a single Sidecar
	GetSidecar(ctx context.Context, in *GetSidecarRequest, opts ...grpc.CallOption) (*GetSidecarResponse, error)
	// Listen listens to Sidecar updates and log output of a running Sidecar
	Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (SsmService_ListenClient, error)
	// StopSidecar stops a currently running Sidecar
	StopSidecar(ctx context.Context, in *StopSidecarRequest, opts ...grpc.CallOption) (*StopSidecarResponse, error)
}

type ssmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSsmServiceClient(cc grpc.ClientConnInterface) SsmServiceClient {
	return &ssmServiceClient{cc}
}

func (c *ssmServiceClient) StartLocalSidecar(ctx context.Context, opts ...grpc.CallOption) (SsmService_StartLocalSidecarClient, error) {
	stream, err := c.cc.NewStream(ctx, &SsmService_ServiceDesc.Streams[0], "/v1.SsmService/StartLocalSidecar", opts...)
	if err != nil {
		return nil, err
	}
	x := &ssmServiceStartLocalSidecarClient{stream}
	return x, nil
}

type SsmService_StartLocalSidecarClient interface {
	Send(*StartLocalSidecarRequest) error
	CloseAndRecv() (*StartSidecarResponse, error)
	grpc.ClientStream
}

type ssmServiceStartLocalSidecarClient struct {
	grpc.ClientStream
}

func (x *ssmServiceStartLocalSidecarClient) Send(m *StartLocalSidecarRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ssmServiceStartLocalSidecarClient) CloseAndRecv() (*StartSidecarResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StartSidecarResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ssmServiceClient) StartFromPreviousSidecar(ctx context.Context, in *StartFromPreviousSidecarRequest, opts ...grpc.CallOption) (*StartSidecarResponse, error) {
	out := new(StartSidecarResponse)
	err := c.cc.Invoke(ctx, "/v1.SsmService/StartFromPreviousSidecar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ssmServiceClient) StartSidecar(ctx context.Context, in *StartSidecarRequest, opts ...grpc.CallOption) (*StartSidecarResponse, error) {
	out := new(StartSidecarResponse)
	err := c.cc.Invoke(ctx, "/v1.SsmService/StartSidecar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ssmServiceClient) ListSidecars(ctx context.Context, in *ListSidecarsRequest, opts ...grpc.CallOption) (*ListSidecarsResponse, error) {
	out := new(ListSidecarsResponse)
	err := c.cc.Invoke(ctx, "/v1.SsmService/ListSidecars", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ssmServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (SsmService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &SsmService_ServiceDesc.Streams[1], "/v1.SsmService/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &ssmServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SsmService_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type ssmServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *ssmServiceSubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ssmServiceClient) GetSidecar(ctx context.Context, in *GetSidecarRequest, opts ...grpc.CallOption) (*GetSidecarResponse, error) {
	out := new(GetSidecarResponse)
	err := c.cc.Invoke(ctx, "/v1.SsmService/GetSidecar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ssmServiceClient) Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (SsmService_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &SsmService_ServiceDesc.Streams[2], "/v1.SsmService/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &ssmServiceListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SsmService_ListenClient interface {
	Recv() (*ListenResponse, error)
	grpc.ClientStream
}

type ssmServiceListenClient struct {
	grpc.ClientStream
}

func (x *ssmServiceListenClient) Recv() (*ListenResponse, error) {
	m := new(ListenResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ssmServiceClient) StopSidecar(ctx context.Context, in *StopSidecarRequest, opts ...grpc.CallOption) (*StopSidecarResponse, error) {
	out := new(StopSidecarResponse)
	err := c.cc.Invoke(ctx, "/v1.SsmService/StopSidecar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SsmServiceServer is the server API for SsmService service.
// All implementations must embed UnimplementedSsmServiceServer
// for forward compatibility
type SsmServiceServer interface {
	// StartLocalSidecar starts a Service Sidecar on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the ssm/config.yaml
	//   3. all bytes constituting the Sidecar YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalSidecar(SsmService_StartLocalSidecarServer) error
	// StartFromPreviousSidecar starts a new Sidecar based on a previous one.
	// If the previous Sidecar does not have the can-replay condition set this call will result in an error.
	StartFromPreviousSidecar(context.Context, *StartFromPreviousSidecarRequest) (*StartSidecarResponse, error)
	// StartSidecarRequest starts a new Sidecar based on its specification.
	StartSidecar(context.Context, *StartSidecarRequest) (*StartSidecarResponse, error)
	// Searches for Sidecar(s) known to this Sidecar
	ListSidecars(context.Context, *ListSidecarsRequest) (*ListSidecarsResponse, error)
	// Subscribe listens to new Sidecar(s) updates
	Subscribe(*SubscribeRequest, SsmService_SubscribeServer) error
	// GetSidecar retrieves details of a single Sidecar
	GetSidecar(context.Context, *GetSidecarRequest) (*GetSidecarResponse, error)
	// Listen listens to Sidecar updates and log output of a running Sidecar
	Listen(*ListenRequest, SsmService_ListenServer) error
	// StopSidecar stops a currently running Sidecar
	StopSidecar(context.Context, *StopSidecarRequest) (*StopSidecarResponse, error)
	mustEmbedUnimplementedSsmServiceServer()
}

// UnimplementedSsmServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSsmServiceServer struct {
}

func (UnimplementedSsmServiceServer) StartLocalSidecar(SsmService_StartLocalSidecarServer) error {
	return status.Errorf(codes.Unimplemented, "method StartLocalSidecar not implemented")
}
func (UnimplementedSsmServiceServer) StartFromPreviousSidecar(context.Context, *StartFromPreviousSidecarRequest) (*StartSidecarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartFromPreviousSidecar not implemented")
}
func (UnimplementedSsmServiceServer) StartSidecar(context.Context, *StartSidecarRequest) (*StartSidecarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSidecar not implemented")
}
func (UnimplementedSsmServiceServer) ListSidecars(context.Context, *ListSidecarsRequest) (*ListSidecarsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSidecars not implemented")
}
func (UnimplementedSsmServiceServer) Subscribe(*SubscribeRequest, SsmService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedSsmServiceServer) GetSidecar(context.Context, *GetSidecarRequest) (*GetSidecarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSidecar not implemented")
}
func (UnimplementedSsmServiceServer) Listen(*ListenRequest, SsmService_ListenServer) error {
	return status.Errorf(codes.Unimplemented, "method Listen not implemented")
}
func (UnimplementedSsmServiceServer) StopSidecar(context.Context, *StopSidecarRequest) (*StopSidecarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopSidecar not implemented")
}
func (UnimplementedSsmServiceServer) mustEmbedUnimplementedSsmServiceServer() {}

// UnsafeSsmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SsmServiceServer will
// result in compilation errors.
type UnsafeSsmServiceServer interface {
	mustEmbedUnimplementedSsmServiceServer()
}

func RegisterSsmServiceServer(s grpc.ServiceRegistrar, srv SsmServiceServer) {
	s.RegisterService(&SsmService_ServiceDesc, srv)
}

func _SsmService_StartLocalSidecar_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SsmServiceServer).StartLocalSidecar(&ssmServiceStartLocalSidecarServer{stream})
}

type SsmService_StartLocalSidecarServer interface {
	SendAndClose(*StartSidecarResponse) error
	Recv() (*StartLocalSidecarRequest, error)
	grpc.ServerStream
}

type ssmServiceStartLocalSidecarServer struct {
	grpc.ServerStream
}

func (x *ssmServiceStartLocalSidecarServer) SendAndClose(m *StartSidecarResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ssmServiceStartLocalSidecarServer) Recv() (*StartLocalSidecarRequest, error) {
	m := new(StartLocalSidecarRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SsmService_StartFromPreviousSidecar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartFromPreviousSidecarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SsmServiceServer).StartFromPreviousSidecar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SsmService/StartFromPreviousSidecar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SsmServiceServer).StartFromPreviousSidecar(ctx, req.(*StartFromPreviousSidecarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SsmService_StartSidecar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSidecarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SsmServiceServer).StartSidecar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SsmService/StartSidecar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SsmServiceServer).StartSidecar(ctx, req.(*StartSidecarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SsmService_ListSidecars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSidecarsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SsmServiceServer).ListSidecars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SsmService/ListSidecars",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SsmServiceServer).ListSidecars(ctx, req.(*ListSidecarsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SsmService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SsmServiceServer).Subscribe(m, &ssmServiceSubscribeServer{stream})
}

type SsmService_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type ssmServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *ssmServiceSubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SsmService_GetSidecar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSidecarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SsmServiceServer).GetSidecar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SsmService/GetSidecar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SsmServiceServer).GetSidecar(ctx, req.(*GetSidecarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SsmService_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SsmServiceServer).Listen(m, &ssmServiceListenServer{stream})
}

type SsmService_ListenServer interface {
	Send(*ListenResponse) error
	grpc.ServerStream
}

type ssmServiceListenServer struct {
	grpc.ServerStream
}

func (x *ssmServiceListenServer) Send(m *ListenResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SsmService_StopSidecar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSidecarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SsmServiceServer).StopSidecar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SsmService/StopSidecar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SsmServiceServer).StopSidecar(ctx, req.(*StopSidecarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SsmService_ServiceDesc is the grpc.ServiceDesc for SsmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SsmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.SsmService",
	HandlerType: (*SsmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartFromPreviousSidecar",
			Handler:    _SsmService_StartFromPreviousSidecar_Handler,
		},
		{
			MethodName: "StartSidecar",
			Handler:    _SsmService_StartSidecar_Handler,
		},
		{
			MethodName: "ListSidecars",
			Handler:    _SsmService_ListSidecars_Handler,
		},
		{
			MethodName: "GetSidecar",
			Handler:    _SsmService_GetSidecar_Handler,
		},
		{
			MethodName: "StopSidecar",
			Handler:    _SsmService_StopSidecar_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartLocalSidecar",
			Handler:       _SsmService_StartLocalSidecar_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _SsmService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Listen",
			Handler:       _SsmService_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ssm.proto",
}
